"""Derived-index proposal and complete lint result assembly."""
import difflib
import json
from pathlib import Path
from typing import Dict, List, Optional

from lint_scan import (
    Refused,
    boundary_findings,
    check_note,
    corpus,
    cross_vault_findings,
    digest,
    finding,
    link_key,
    note_index,
    relative,
    route,
    text,
)


def index_proposal(root: Path, path: str, selected: List[str]) -> Optional[dict]:
    destination = route(root, path)
    listed = [item for item in selected if item != path]
    content = (
        "<!-- generated by lint; derived index -->\n# Derived index\n\n"
        + "".join("- [[{}]]\n".format(item[:-3]) for item in listed)
    ).encode("utf-8")
    before = destination.read_bytes() if destination.is_file() else None
    if before == content:
        return None
    if destination.exists() and not destination.is_file():
        raise Refused("unsafe_destination", "derived index is not a regular file")
    old = b"" if before is None else before
    diff = "".join(
        difflib.unified_diff(
            old.decode("utf-8").splitlines(keepends=True),
            content.decode("utf-8").splitlines(keepends=True),
            fromfile="/dev/null" if before is None else path,
            tofile=path,
        )
    )
    binding = {
        "path": path,
        "preimage": "absent" if before is None else digest(before),
        "postimage": digest(content),
        "diff": diff,
    }
    return {
        "path": path,
        "effect": "create" if before is None else "update",
        "preimage": binding["preimage"],
        "postimage": binding["postimage"],
        "diff": diff,
        "content": content.decode("utf-8"),
        "proposal_sha256": digest(
            json.dumps(binding, ensure_ascii=False, sort_keys=True).encode("utf-8")
        ),
    }


def parse_request(request: dict) -> tuple:
    expected = {
        "schema",
        "mode",
        "scope",
        "required_properties",
        "derived_index",
        "boundaries",
    }
    if (
        not isinstance(request, dict)
        or set(request) - expected - {"cross_vault"}
        or not expected <= set(request)
    ):
        raise Refused("invalid_input", "unexpected or missing request fields")
    if request["schema"] != "lint/request@1" or request["mode"] not in ("report", "fix"):
        raise Refused("invalid_input", "unsupported schema or mode")
    scope = request["scope"]
    required = request["required_properties"]
    boundaries = request["boundaries"]
    if (
        not isinstance(scope, list)
        or not scope
        or any(not isinstance(item, str) for item in scope)
        or not isinstance(required, list)
        or any(not isinstance(item, str) or not item for item in required)
        or not isinstance(boundaries, list)
    ):
        raise Refused("invalid_input", "scope, properties, and boundaries must be lists")
    return scope, required, boundaries


def analyze(root: Path, request: dict) -> dict:
    scope, required, boundaries = parse_request(request)
    selected = corpus(root, [relative(item) for item in scope])
    known = note_index(root)
    bodies = {
        path: route(root, path).read_text(encoding="utf-8")
        for path in selected
    }
    findings: List[dict] = []
    incoming: Dict[str, int] = dict((path, 0) for path in selected)
    for path in selected:
        note_findings, local_links = check_note(path, bodies[path], required, known)
        findings.extend(note_findings)
        for link in local_links:
            resolved = known.get(link_key(link))
            if resolved in incoming:
                incoming[resolved] += 1
    index_path = relative(text(request["derived_index"], "derived_index"))
    for path, count in sorted(incoming.items()):
        if path != index_path and count == 0:
            findings.append(finding("orphan_link", path, "no local inlinks"))
    findings.extend(boundary_findings(selected, bodies, known, boundaries))
    limits = [
        "Orphan-link coverage is limited to links within the selected scope; "
        "unrelated note bodies were not read."
    ]
    cross, cross_limits, cross_vault = cross_vault_findings(
        selected, bodies, request.get("cross_vault")
    )
    findings.extend(cross)
    limits.extend(cross_limits)
    proposal = index_proposal(root, index_path, selected)
    if proposal:
        findings.append(finding("index", index_path, "derived index differs"))
    return {
        "schema": "lint/result@1",
        "status": "limited" if limits else "reported",
        "mode": request["mode"],
        "scope": [relative(item) for item in scope],
        "checked_notes": selected,
        "checks": [
            "structure",
            "citations",
            "properties",
            "index",
            "broken_link",
            "orphan_link",
            "persona_boundary",
        ] + (["cross_vault_link"] if cross_vault["checked"] else []),
        "findings": findings,
        "limits": limits,
        "cross_vault": cross_vault,
        "derived_index_proposals": [] if proposal is None else [proposal],
        "note_patch_proposals": [],
        "mutations_performed": [],
    }
